# Kibana конфигурация для визуализации логов
# Электронный журнал производства работ - Промышленное решение

# Основные настройки сервера
server.port: 5601
server.host: "0.0.0.0"
server.name: "electronic-journal-kibana"
server.publicBaseUrl: "http://localhost:5601"

# Настройки Elasticsearch
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "kibana_password"
elasticsearch.requestTimeout: 30000
elasticsearch.shardTimeout: 30000
elasticsearch.ssl.verificationMode: none

# Настройки логирования
logging.appenders:
  file:
    type: file
    fileName: /usr/share/kibana/logs/kibana.log
    layout:
      type: json
  default:
    type: console
    layout:
      type: pattern
      highlight: true

logging.root:
  level: info
  appenders: [default, file]

logging.loggers:
  - name: http.server.response
    level: debug
    appenders: [file]
  - name: elasticsearch.query
    level: debug
    appenders: [file]

# Настройки мониторинга
monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true
monitoring.kibana.collection.enabled: true
monitoring.cluster_uuid: "electronic-journal-cluster"

# Настройки безопасности
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long_for_encryption"
xpack.reporting.encryptionKey: "something_at_least_32_characters_long_for_reporting"
xpack.security.encryptionKey: "something_at_least_32_characters_long_for_security"

# Настройки пространств имен
xpack.spaces.enabled: true
xpack.spaces.maxSpaces: 100

# Настройки для промышленного использования
server.maxPayload: 1048576
server.compression.enabled: true
server.compression.referrerWhitelist: ["localhost", "*.electronic-journal.local"]

# Настройки кеширования
elasticsearch.requestHeadersWhitelist: ["authorization", "content-type", "kbn-version", "kbn-xsrf-token"]
elasticsearch.customHeaders: {}
elasticsearch.pingTimeout: 1500
elasticsearch.startupTimeout: 5000

# Настройки индексов
kibana.index: ".kibana"
kibana.defaultAppId: "dashboard"
kibana.autocompleteTimeout: 1000
kibana.autocompleteTerminateAfter: 100000

# Настройки карт для GIS данных
map.includeElasticMapsService: true
map.proxyElasticMapsServiceInMaps: false
map.tilemap.url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
map.tilemap.options.attribution: "© OpenStreetMap contributors"
map.tilemap.options.minZoom: 1
map.tilemap.options.maxZoom: 18
map.regionmap.includeElasticMapsService: true
map.manifestServiceUrl: "https://catalogue.maps.elastic.co/v7.17/manifest"

# Настройки временных диапазонов
timelion.enabled: true
timelion.graphiteUrls: []

# Настройки CSV экспорта для отчетности
xpack.reporting.csv.maxSizeBytes: 10485760
xpack.reporting.csv.scroll.duration: "30s"
xpack.reporting.csv.scroll.size: 500
xpack.reporting.capture.browser.chromium.disableSandbox: true

# Настройки для дашбордов промышленного мониторинга
data.search.aggs.shards.request.totalhits: true
data.search.sessions.enabled: true
data.search.usageTelemetry.enabled: false

# Настройки уведомлений
xpack.actions.enabled: true
xpack.actions.allowedHosts: ["*"]
xpack.actions.enabledActionTypes: ["email", "webhook", "slack"]

# Настройки алертов для производственного мониторинга
xpack.alerting.rules.run.timeout: "5m"
xpack.alerting.rules.run.actions.max: 1000
xpack.task_manager.max_workers: 10
xpack.task_manager.poll_interval: 3000
xpack.task_manager.max_attempts: 3

# Настройки Machine Learning (отключено для базовой установки)
xpack.ml.enabled: false

# Настройки Canvas для создания презентаций
xpack.canvas.enabled: true

# Настройки Lens для продвинутой визуализации
xpack.lens.enabled: true

# Настройки управления индексами
xpack.index_management.enabled: true
xpack.index_lifecycle_management.enabled: true

# Настройки Watcher для алертов (если включен в Elasticsearch)
xpack.watcher.enabled: false

# Настройки для интеграции с внешними системами
newsfeed.enabled: false
telemetry.enabled: false
telemetry.optIn: false

# Настройки производительности
elasticsearch.maxConcurrentShardRequests: 5
server.keepaliveTimeout: 120000
server.socketTimeout: 120000

# Настройки для работы с большими данными
data.search.timeout: 600000
courier.batchRequestsTimeout: 30000
courier.maxConcurrentShardRequests: 5

# Пользовательские настройки для электронного журнала
savedObjects.maxImportPayloadBytes: 26214400
savedObjects.maxImportExportSize: 10000

# Настройки локализации
i18n.locale: "ru"

# Настройки темы
uiSettings.overrides:
  "theme:darkMode": false
  "dateFormat": "DD.MM.YYYY HH:mm:ss"
  "dateFormat:dow": "Понедельник"
  "timepicker:timeDefaults": "{\"from\":\"now-15m\",\"to\":\"now\"}"
  "defaultIndex": "electronic-journal-*"
  "discover:sampleSize": 500
  "histogram:barTarget": 50
  "state:storeInSessionStorage": true
  "metaFields": ["_source", "_id", "_type", "_index", "_score"]
  "query:queryString:options": "{\"analyze_wildcard\":true}"
  "sort:options": "{\"unmapped_type\":\"boolean\"}"
  "courier:ignoreFilterIfFieldNotInIndex": false
  "fields:popularLimit": 10
  "histogram:maxBars": 100
  "visualize:enableLabs": true
  "notifications:lifetime:banner": 3000000
  "notifications:lifetime:info": 10000
  "doc_table:highlight": true
  "discover:searchFieldsFromSource": false

# Настройки для дашбордов производственного мониторинга
dashboard.defaultDarkMode: false

# Настройки автообновления для мониторинга в реальном времени
discover.enableAutoRefresh: true

# Продвинутые настройки поиска
data.search.sessions.defaultExpiration: "7d"
data.search.sessions.management.maxSessions: 10000
data.search.sessions.management.refreshInterval: "1m"
data.search.sessions.management.refreshTimeout: "10m"

# Настройки безопасности контента
csp.strict: false
csp.warnLegacyBrowsers: true

# Настройки для работы в корпоративной среде
server.cors.enabled: false
server.cors.allowCredentials: false
server.cors.allowOrigin: ["*"]

# Пид файл
pid.file: /run/kibana/kibana.pid

# Настройки оптимизации сборки
optimize.enabled: true

# Отключение различных плагинов для оптимизации (при необходимости)
# plugins.scanDirs: []
